Slamm fixes in two tasks
jetbrains-academy/Testing-Course pull request #84
Opened 2024-08-02 13:07 UTC by kochaika

- Add placeholders and fix test in `introduction/web page structure/visual attributes` task
- https://github.com/jetbrains-academy/Testing-Course/issues/81
- https://github.com/jetbrains-academy/Testing-Course/issues/83

2024-08-02 13:50 UTC, stephen-hero requested changes
language checked

2024-08-02 13:50 UTC, stephen-hero commented on introduction/starting_browser/installing chromedriver for MacOs/task.md
> +2. If you get the message like "Apple cannot check app for malicious software...", use [this Apple guide](https://support.apple.com/en-am/guide/mac-help/mchleab3a043/mac) to add the `chromedriver` to
If you get a message like..... to add `chromedriver` to the exceptions.

2024-08-02 14:08 UTC, stephen-hero approved these changes

2024-08-28 15:28 UTC, Geravant approved these changes

2024-09-04 08:51 UTC, merged